version: "3.5"
services:
  mrss-redis:
    container_name: mrss-redis-container
    restart: on-failure:5
    image: redis:alpine
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    # Comment below to show redis logs
    # logging:
    #   driver: none
    
  mrss-mongo:
    container_name: mrss-mongodb-container
    restart: on-failure:5
    command: mongod --port 27017
    # Comment below to show mongo logs
    # logging:
    #   driver: none
    image: mongo:latest
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - 'db-data:/data/db'
      
  mrss-bot:
    container_name: mrss-bot-container
    restart: on-failure:3
    # The image can also be used
    image: test
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    #build: .
    depends_on:
      - mrss-mongo
    environment:
      - DRSS_START=bot
      - DRSS_BOT_TOKEN=KNTkxOTUxMTU2MTg4NTQ1MDI1.XQ4PeQ.e1A_1sF0W7_rmCPJsMdhur8Bevo
      - DRSS_DATABASE_URI=mongodb://mrss-mongo:27017/rss
      
  mrss-web:
    container_name: mrss-web-container
    # The image can also be used
    image: test
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    #build: .
    restart: on-failure:3
    depends_on:
      - mrss-redis
      - mrss-mongo
    ports:
      - "8081:8081"
    environment:
      - DRSS_START=web
      - DRSSWEB_BOT_TOKEN=KNTkxOTUxMTU2MTg4NTQ1MDI1.XQ4PeQ.e1A_1sF0W7_rmCPJsMdhur8Bevo
      - DRSSWEB_DATABASE_REDIS=redis://mrss-redis:6379
      - DRSSWEB_DATABASE_URI=mongodb://mrss-mongo:27017/rss
      - DRSSWEB_BOT_REDIRECTURI=http://localhost:8081/authorize
      - DRSSWEB_BOT_CLIENTID=591951156188545025
      - DRSSWEB_BOT_CLIENTSECRET=KH14yvSVb6NTMYva7azG50s9nx7ayOx5E

volumes:
  db-data:
